---
title: ""
params:
  crop: "{{crop}}"
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE)

if (!exists("params") || grepl("\\{", params$crop)) {
    crop <- "Wheat"
} else {
    crop <- params[["crop"]]
}


```


```{r data-obs-sim}

# Read the obs/prediction files
obs_sim <- get_obs(crop)

apsimx <- get_model(crop)
cultivars <- rapsimng::get_cultivar(apsimx, alias = TRUE) |> tibble::tibble()
cultivars <- cultivars |> 
    dplyr::select(Cultivar = standard_name) |> 
    dplyr::distinct()
experiments <- obs_sim |> 
    dplyr::distinct(ExperimentName, Latitude, Longitude)
```

The performance of **`r crop`** in the [APSIM NG](https://apsim.info) is summarized using datasets in the [validation test set](https://github.com/APSIMInitiative/ApsimX) in the following apsimx files.

```{r list-files}

files <- get_apsimx(crop)
base_folder <- Sys.getenv("APSIMX_DIR")
files |> 
    dplyr::mutate(file = strip_base_path(file, base_folder)) |>
    dplyr::select(file) |> 
    dplyr::distinct() |>
    knitr::kable(
        col.names = ""
    )
```


```{r child-cultivars, results = "asis"}
# include the performance section if there are data for this cultivar
cat(render_child(
    here::here("_template/section/cultivars.qmd"),
    cultivars = cultivars
))
```


```{r child-experiment, results = "asis"}
cat(render_child(
    here::here("_template/section/experiments.qmd"),
    experiments = experiments,
    cultivar = "All"
))
```





```{r child-performance, results = "asis"}
cat(render_child(
    here::here("_template/section/performance.qmd"),
    obs_sim = obs_sim,
    cultivar = "All"
))
```



