---
title: "{{title}}"
format: html
params:
  crop: "{{crop}}"
  cultivar: "{{cultivar}}"
has_data: true
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE)

if (!exists("params") || grepl("\\{", params$crop)) {
    crop <- "Wheat"
    cultivar <- "Bolac"
} else {
    crop <- params[["crop"]]
    cultivar <- params[["cultivar"]]
}
crop_cache_dir <- ".cache"

```

```{r data-obs-sim}

# Read the obs/prediction files
file_path <- file.path(crop_cache_dir, paste0(crop, ".Rds")) |> 
    here::here()
message("Reading cached output: ", file_path)
obs_sim <- readRDS(file_path)

APSIMX_DIR <- Sys.getenv("APSIMX_DIR")
if (APSIMX_DIR == "") {
    stop("Please set APSIMX_DIR environment variable to point to APSIM NG installation directory.")
}
model <- file.path(APSIMX_DIR, sprintf("Models/Resources/%s.json", crop))
if (!file.exists(model)) {
    stop(sprintf("Model file %s does not exist.", model))
}
apsimx <- rapsimng::read_apsimx(model)
cultivars <- rapsimng::get_cultivar(apsimx, alias = TRUE) |> tibble::tibble()
cultivar_info <- cultivars |> dplyr::filter(standard_name == cultivar)
```


This report is generated for performance of `r crop` model in APSIM NG for cultivar `r cultivar`. 


## Cultivar Information


The cultivar specific parameters used in the simulation are listed in the table below:

```{r tbl-cultivar_info}
cultivar_info |> 
    dplyr::select(-name) |> 
    dplyr::distinct() |>
    dplyr::select(parameter, value) |>
    knitr::kable(caption = sprintf("Cultivar specific parameters for `%s`", cultivar))

```

```{r cultivar_aliases,results='asis'}

aliases <- cultivar_info |> 
    dplyr::distinct(name) |> 
    dplyr::filter(name != cultivar) |> 
    dplyr::pull(name)
if (length(aliases) > 0) {
    #cat("\n")
    cat("The following aliases are also available for this cultivar: **")
    aliases |>
        paste(collapse = ", ") |>
        cat()
    cat("**")
    #cat("\n")
}
```

## Experiments


::: {.content-hidden when-meta="has_data"}
> No observations available for this cultivar.
:::



::: {.content-visible when-meta="has_data"}


:::
```{r data-obs-sim-cultivar}

obs_sim_cultivar <- obs_sim |> 
    dplyr::filter(Genotype == tolower(cultivar))

experiments <- obs_sim_cultivar |> 
    dplyr::distinct(ExperimentName, Latitude, Longitude)
View(experiments)
```

There are `r nrow(experiments)` experiments which tested cultivar `r cultivar` and its aliases.


```{r fig-experiments, fig.height=6, fig.cap="Locations of experiments without controlled environments."}
experiments |> 
    dplyr::filter(!is.na(Longitude), !is.na(Latitude)) |>
    dplyr::filter(Longitude != 0 & Latitude != 0) |>
    leaflet::leaflet() |>
    leaflet::addTiles() |>
    leaflet::addMarkers(~Longitude, ~Latitude, 
        popup = ~ExperimentName)
```
