
## Experiments


There are `r nrow(experiments)` experiments which tested cultivar `r cultivar` and its aliases.


```{r fig-experiments, fig.height=6, fig.cap="Locations of experiments without controlled environments."}
experiments |> 
    dplyr::filter(!is.na(Longitude), !is.na(Latitude)) |>
    dplyr::filter(Longitude != 0 & Latitude != 0) |>
    leaflet::leaflet(options = leaflet::leafletOptions(scrollWheelZoom = FALSE)) |>
    leaflet::addTiles() |>
    leaflet::addMarkers(~Longitude, ~Latitude, 
        popup = ~ExperimentName)
```

## Performance

```{r data-trait}
traits <- obs_sim_cultivar |> 
    dplyr::distinct(trait) |> 
    dplyr::pull(trait) |> 
    sort()
```


The table below summarizes the performance of APSIM NG for cultivar `r cultivar` across all experiments.

```{r tbl-performance-summary}

obs_sim_cultivar |> 
    dplyr::group_by(trait) |>
    myutils::model_summarise(x = "Observed", y = "Predicted", digits = 2)|>
    dplyr::ungroup() |>
    dplyr::arrange(trait) |>
    knitr::kable(caption = sprintf("Performance summary for cultivar `%s`", cultivar))
```

::: {.panel-tabset}

```{r performance, results = "asis", fig.cap = "Observed vs Predicted plots for different traits."}
i <- 1
for (i in seq(along = traits)) {
    trait_i <- traits[i]
    cat("### ", trait_i, "\n\n")
    
    obs_sim_trait <- obs_sim_cultivar |> 
        dplyr::filter(trait == trait_i)
    rng <- range(c(obs_sim_trait$Observed, obs_sim_trait$Predicted), na.rm = TRUE)
    p <- obs_sim_trait |> 
        ggplot2::ggplot() +
        ggplot2::geom_point(ggplot2::aes(x = Observed, y = Predicted)) +
        ggplot2::theme_bw() +
        ggplot2::geom_abline() +
        ggplot2::labs(
            x = "Observed",
            y = "Predicted"
        ) +
        ggplot2::xlim(rng) +
        ggplot2::ylim(rng)
    print(p)    
    cat("\n\n")
}
```

:::
