---
title: "{{title}}"
format: html
params:
  crop: "{{crop}}"
  cultivar: "{{cultivar}}"
has_data: true
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE)

if (!exists("params") || grepl("\\{", params$crop)) {
    crop <- "Wheat"
    cultivar <- "Yitpi"
} else {
    crop <- params[["crop"]]
    cultivar <- params[["cultivar"]]
}

```

```{r data-obs-sim}
# Read the obs/prediction files
obs_sim <- get_obs(crop)
apsimx <- get_model(crop)
cultivars <- rapsimng::get_cultivar(apsimx, alias = TRUE) |> tibble::tibble()
cultivar_info <- cultivars |> dplyr::filter(standard_name == cultivar)
```


This report is generated for performance of `r crop` model in APSIM NG for cultivar `r cultivar`. 


## Cultivar Information


The cultivar specific parameters used in the simulation are listed in the table below:

```{r tbl-cultivar_info}
cultivar_info |> 
    dplyr::select(-name) |> 
    dplyr::distinct() |>
    dplyr::select(parameter, value) |>
    knitr::kable(caption = sprintf("Cultivar specific parameters for `%s`", cultivar))

```

```{r cultivar_aliases,results='asis'}

aliases <- cultivar_info |> 
    dplyr::distinct(name) |> 
    dplyr::filter(name != cultivar) |> 
    dplyr::pull(name)
if (length(aliases) > 0) {
    #cat("\n")
    cat("The following aliases are also available for this cultivar: **")
    aliases |>
        paste(collapse = ", ") |>
        cat()
    cat("**")
    #cat("\n")
}
```


```{r data-obs-sim-cultivar}

obs_sim_cultivar <- obs_sim |> 
    dplyr::filter(Genotype == tolower(cultivar))
experiments <- obs_sim_cultivar |> 
    dplyr::distinct(ExperimentName, Latitude, Longitude)
has_data <- nrow(obs_sim_cultivar) > 0
```



```{r child-performance, results = "asis"}
if (!has_data) {
    cat(render_child(
        here::here("_template/section/no-data-warning.qmd")
    ))
} else {
    cat(render_child(
        here::here("_template/section/experiments.qmd"),
        experiments = experiments,
        cultivar = cultivar
    ))
    cat(render_child(
        here::here("_template/section/performance.qmd"),
        obs_sim = obs_sim_cultivar,
        cultivar = cultivar
    ))
}
```
