---
title: "{{title}}"
format: html
params:
  crop: "{{crop}}"
  experiment: "{{experiment}}"
has_data: true
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE)

if (!exists("params") || grepl("\\{", params$crop)) {
    crop <- "Chickpea"
    experiment <- "Bremar_2003_"
} else {
    crop <- params[["crop"]]
    experiment <- params[["experiment"]]
}

```

```{r data-obs-sim}
# Read the obs/prediction files
obs_sim <- get_obs(crop)
obs_sim_experiment <- obs_sim |> 
    dplyr::filter(ExperimentName == experiment)
cultivars <- obs_sim_experiment |> 
    dplyr::distinct(Genotype) |> 
    dplyr::rename(Cultivar = Genotype)
apsimx <- get_model(crop)
experiment_data <- get_experiment_data(crop)
experiment_data <- experiment_data |> 
    dplyr::filter(Experiment == experiment)

```

This report is generated for performance of `r crop` model in APSIM NG for experiment `r experiment`. 


## Experiment Information

```{r info-experiment, results = "asis"}
if (nrow(experiment_data) == 0) {
    cat("<div class='intro-text'>No data available information for this experiment.</div>")
} else {
    cat("<div class='intro-text'>The experiment specific information is provided in the memo of apsimx file.</div>")
    cat("\n\n)")
    cat(experiment_data$Memo)
}

```


```{r child-performance, results = "asis"}
cat(render_child(
    here::here("_template/section/cultivars.qmd"),
    cultivars = cultivars
))
cat(render_child(
    here::here("_template/section/performance.qmd"),
    obs_sim = obs_sim_experiment,
    experiment = experiment
))
```
